/** C1 vocabulary — 67 words, split into a 7-day campaign */
window.VOCAB = [
  { id: 1, word: "abundant", meaning: "present in large quantities" },
  { id: 2, word: "accumulate", meaning: "to gradually collect" },
  { id: 3, word: "accurate", meaning: "correct, free from errors" },
  { id: 4, word: "accustomed", meaning: "used to something" },
  { id: 5, word: "acquire", meaning: "to come into possession of" },
  { id: 6, word: "adamant", meaning: "refusing to change an opinion" },
  { id: 7, word: "adequate", meaning: "enough to suit your needs" },
  { id: 8, word: "adjacent", meaning: "close to, next to" },
  { id: 9, word: "adjust", meaning: "to change something so it serves its purpose better" },
  { id: 10, word: "advantage", meaning: "something that makes it easier to achieve success" },
  { id: 11, word: "advocate", meaning: "to publicly support" },
  { id: 12, word: "adverse", meaning: "unfavorable; against one's desires" },
  { id: 13, word: "aggregate", meaning: "to combine" },
  { id: 14, word: "aggressive", meaning: "assertive and pushy" },
  { id: 15, word: "allocate", meaning: "to put aside for a specific purpose" },
  { id: 16, word: "alternative", meaning: "another option or choice" },
  { id: 17, word: "amateur", meaning: "someone who is inexperienced or not highly skilled in a particular area" },
  { id: 18, word: "ambiguous", meaning: "having several potential meanings; unclear and difficult to understand" },
  { id: 19, word: "ambitious", meaning: "having large goals" },
  { id: 20, word: "amend", meaning: "to change for the better; to improve" },
  { id: 21, word: "ample", meaning: "plentiful" },
  { id: 22, word: "anomaly", meaning: "deviation from the norm" },
  { id: 23, word: "annual", meaning: "occurring yearly" },
  { id: 24, word: "antagonize", meaning: "to tease or be hostile towards a person or group" },
  { id: 25, word: "attitude", meaning: "manner or feeling" },
  { id: 26, word: "attribute", meaning: "to give credit" },
  { id: 27, word: "arbitrary", meaning: "based on a whim or random desire" },
  { id: 28, word: "arduous", meaning: "requiring a lot of effort" },
  { id: 29, word: "assuage", meaning: "to lessen a negative feeling" },
  { id: 30, word: "assume", meaning: "to suppose without solid proof" },
  { id: 31, word: "augment", meaning: "to increase or make larger" },
  { id: 32, word: "benefit", meaning: "something positive or advantageous" },
  { id: 33, word: "berate", meaning: "to scold" },
  { id: 34, word: "bestow", meaning: "to give as a gift" },
  { id: 35, word: "boast", meaning: "to brag or talk with excessive pride" },
  { id: 36, word: "boost", meaning: "to help raise or increase something" },
  { id: 37, word: "brash", meaning: "rude and tactless" },
  { id: 38, word: "brief", meaning: "short (in terms of time)" },
  { id: 39, word: "brusque", meaning: "abrupt to the point of rudeness" },
  { id: 40, word: "cacophony", meaning: "a harsh, unpleasant mixture of noise" },
  { id: 41, word: "cease", meaning: "to stop" },
  { id: 42, word: "censure", meaning: "to express strong disapproval" },
  { id: 43, word: "chronological", meaning: "arranged in order of time or date" },
  { id: 44, word: "clarify", meaning: "to make clear; to remove confusion" },
  { id: 45, word: "coalesce", meaning: "to combine or grow together" },
  { id: 46, word: "coerce", meaning: "to force someone to do something against their will" },
  { id: 47, word: "cognizant", meaning: "being aware or having knowledge of something" },
  { id: 48, word: "cohesion", meaning: "uniting; becoming one" },
  { id: 49, word: "coincide", meaning: "to occur at the same time" },
  { id: 50, word: "collapse", meaning: "to fall down or break down" },
  { id: 51, word: "collide", meaning: "to hit one another with a forceful impact" },
  { id: 52, word: "commitment", meaning: "dedication to a cause or activity" },
  { id: 53, word: "community", meaning: "a group of people who live or work together" },
  { id: 54, word: "conceal", meaning: "to hide" },
  { id: 55, word: "concur", meaning: "to agree" },
  { id: 56, word: "conflict", meaning: "a disagreement or fight" },
  { id: 57, word: "constrain", meaning: "to restrict or repress" },
  { id: 58, word: "contemplate", meaning: "to consider thoughtfully" },
  { id: 59, word: "continuously", meaning: "to go on without stopping" },
  { id: 60, word: "contradict", meaning: "to give the opposite opinion" },
  { id: 61, word: "contribute", meaning: "to give something (usually money or time) to a common fund or cause" },
  { id: 62, word: "convey", meaning: "to make known" },
  { id: 63, word: "copious", meaning: "abundant" },
  { id: 64, word: "core", meaning: "central; of main importance" },
  { id: 65, word: "corrode", meaning: "to gradually wear away" },
  { id: 66, word: "cumbersome", meaning: "burdensome; clumsy" },
  { id: 67, word: "curriculum", meaning: "the courses given by a school or program" },
];

/** Day sizes: 10,10,10,10,10,10,7 */
window.DAY_SIZES = [10, 10, 10, 10, 10, 10, 7];

window.DAY_TITLES = [
  "The Opening Hand",
  "Fog of Ambition",
  "Hard Edges",
  "Gift & Grit",
  "Noise & Order",
  "Force & Form",
  "The Final Core",
];

window.DAY_BLURBS = [
  "Десять слов про количество, точность и соседство.",
  "Выбор, неясность и большие цели.",
  "Труд, капризы и то, что мы приписываем.",
  "Польза, упрёки и гордость.",
  "Грубость, шум и ясность.",
  "Сила, осознание и столкновения.",
  "Сообщество, конфликт и суть — финал недели.",
];
